name: Feature request
description: Propose a new capability for the landing zone module
labels: ["type/feature"]
body:
  - type: input
    id: summary
    attributes: { label: Summary, placeholder: "Short title" }
    validations: { required: true }
  - type: textarea
    id: details
    attributes: { label: Details, description: "What & why" }
  - type: textarea
    id: ac
    attributes: { label: Acceptance Criteria, placeholder: "- [ ] ..." }
  - type: dropdown
    id: epic
    attributes:
      label: Epic
      options: ["Scaffolding","Governance","Identity","Networking","Security","Observability","Examples","CI/CD","Docs"]
  - type: input
    id: estimate
    attributes: { label: Estimate (pts) }
